width: 25
height: 25
depot: [2, 2]
hospitals:
  - [22, 3]
  - [12, 22]
  - [3, 12]
buildings:
  - [6, 6]
  - [7, 6]
  - [8, 6]
  - [6, 7]
  - [6, 8]
  - [15, 15]
  - [16, 15]
  - [17, 15]
  - [15, 16]
  - [15, 17]
  - [10, 5]
  - [11, 5]
  - [12, 5]
  - [10, 6]
  - [10, 7]
initial_fires:
  - [8, 8]
  - [9, 8]
  - [8, 9]
  - [18, 18]
  - [19, 18]
  - [18, 19]
rubble:
  - [12, 12]
  - [13, 12]
  - [12, 13]
  - [13, 13]
  - [5, 20]
  - [6, 20]
  - [20, 5]
  - [21, 5]
survivors: 20
